/**
 * ═══════════════════════════════════════════════════
 *  macOS Custom Auto-Updater (no Apple Developer ID)
 * ═══════════════════════════════════════════════════
 *
 * Squirrel.Mac (which electron-updater uses on macOS) refuses to install
 * updates unless the app is signed with a Developer ID certificate. We
 * don't have one yet, so on macOS we run the update pipeline ourselves:
 *
 *   1. Fetch <feed>/latest-mac.yml  (generated by electron-builder, same
 *      R2/Cloudflare bucket as the Windows latest.yml)
 *   2. Compare versions → notify renderer
 *   3. Download the .zip, verifying its SHA512 from the yml
 *      (same integrity guarantee electron-updater gives)
 *   4. Extract with `ditto`, swap /Applications/<App>.app atomically
 *   5. Relaunch via `open` after a full quit (full close is more reliable
 *      than in-place relaunch — see electron-builder#3983)
 *
 * The renderer contract is IDENTICAL to the Windows electron-updater path:
 * same 'update-status' payloads, same 'install-update' / 'check-for-updates'
 * IPC channels — the UI cannot tell the difference.
 *
 * Windows code is untouched; main.js only routes here when
 * process.platform === 'darwin'.
 */

const { app, ipcMain, dialog } = require('electron');
const { execFile, spawn } = require('child_process');
const crypto = require('crypto');
const https = require('https');
const http = require('http');
const path = require('path');
const fs = require('fs');
const os = require('os');

const PREFIX = '[macOS Updater]';
const DEFAULT_FEED_URL = 'https://download.stonicai.com';
const CHANNEL_FILE = 'latest-mac.yml';

const log = {
  info: (...a) => console.log(PREFIX, ...a),
  warn: (...a) => console.warn(PREFIX, ...a),
  error: (...a) => console.error(PREFIX, ...a),
};

// ── Module state ────────────────────────────────────────
const state = {
  autoDownload: true,
  checking: false,
  downloading: false,
  // After a successful download+verify+extract:
  pending: null, // { version, appPath (extracted .app), workDir }
  sendStatus: () => {},
};

// ── Helpers ─────────────────────────────────────────────

function getFeedUrl() {
  // Packaged apps carry resources/app-update.yml with the publish URL.
  try {
    const cfgPath = path.join(process.resourcesPath, 'app-update.yml');
    if (fs.existsSync(cfgPath)) {
      const m = fs.readFileSync(cfgPath, 'utf8').match(/^url:\s*(\S+)/m);
      if (m) return m[1].replace(/['"]/g, '').replace(/\/+$/, '');
    }
  } catch { /* fall through */ }
  return DEFAULT_FEED_URL;
}

function httpGet(url, { asStream = false, redirects = 5 } = {}) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    const req = client.get(url, (res) => {
      if ([301, 302, 303, 307, 308].includes(res.statusCode) && res.headers.location && redirects > 0) {
        res.resume();
        const next = new URL(res.headers.location, url).toString();
        return httpGet(next, { asStream, redirects: redirects - 1 }).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
      }
      if (asStream) return resolve(res);
      let data = '';
      res.setEncoding('utf8');
      res.on('data', (c) => { data += c; });
      res.on('end', () => resolve(data));
      res.on('error', reject);
    });
    req.on('error', reject);
    req.setTimeout(30000, () => req.destroy(new Error('Request timeout')));
  });
}

/**
 * Minimal parser for electron-builder's latest-mac.yml. We only need
 * version + the .zip entry (url, sha512, size). Avoids a yaml dependency.
 */
function parseChannelYml(text) {
  const version = (text.match(/^version:\s*(.+)$/m) || [])[1];
  if (!version) throw new Error('latest-mac.yml: version missing');

  let zipUrl = null;
  let zipSha = null;
  let zipSize = 0;
  // files entries look like:  - url: Name-1.0.0-arm64.zip\n    sha512: ...\n    size: 123
  const entryRe = /-\s+url:\s*(.+)\s*\n\s+sha512:\s*(\S+)\s*\n(?:\s+size:\s*(\d+))?/g;
  let m;
  while ((m = entryRe.exec(text)) !== null) {
    if (m[1].trim().endsWith('.zip')) {
      zipUrl = m[1].trim();
      zipSha = m[2].trim();
      zipSize = parseInt(m[3] || '0', 10);
      break;
    }
  }
  // Fallback to top-level path/sha512 (older layouts)
  if (!zipUrl) {
    const p = (text.match(/^path:\s*(.+)$/m) || [])[1];
    const s = (text.match(/^sha512:\s*(\S+)$/m) || [])[1];
    if (p && p.trim().endsWith('.zip')) { zipUrl = p.trim(); zipSha = (s || '').trim(); }
  }
  if (!zipUrl) throw new Error('latest-mac.yml: no .zip entry found');
  return { version: version.trim(), zipUrl, zipSha, zipSize };
}

function isNewerVersion(remote, local) {
  const pa = String(remote).split('.').map((n) => parseInt(n, 10) || 0);
  const pb = String(local).split('.').map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const a = pa[i] || 0, b = pb[i] || 0;
    if (a > b) return true;
    if (a < b) return false;
  }
  return false; // equal → not newer (no downgrades either)
}

function execFileP(cmd, args, opts = {}) {
  return new Promise((resolve, reject) => {
    execFile(cmd, args, { timeout: 300000, ...opts }, (err, stdout, stderr) => {
      if (err) reject(new Error(`${cmd} failed: ${stderr || err.message}`));
      else resolve(stdout);
    });
  });
}

/** Running .app bundle path, derived from the executable path. */
function getCurrentAppBundlePath() {
  // .../Stonic AI.app/Contents/MacOS/Stonic AI → .../Stonic AI.app
  const exe = process.execPath;
  const idx = exe.indexOf('.app/Contents/');
  if (idx === -1) return null;
  return exe.slice(0, idx + 4);
}

// ── Core steps ──────────────────────────────────────────

async function checkForUpdates() {
  if (state.checking || state.downloading) return;
  state.checking = true;
  state.sendStatus({ status: 'checking' });
  try {
    const feed = getFeedUrl();
    const yml = await httpGet(`${feed}/${CHANNEL_FILE}`);
    const info = parseChannelYml(yml);
    const current = app.getVersion();

    if (!isNewerVersion(info.version, current)) {
      log.info(`Up to date (local ${current}, remote ${info.version}).`);
      state.sendStatus({ status: 'not-available' });
      return;
    }

    log.info(`Update available: ${current} → ${info.version}`);
    state.sendStatus({ status: 'available', version: info.version });

    if (state.autoDownload) {
      await downloadUpdate(info, feed);
    } else {
      state.lastInfo = { info, feed };
    }
  } catch (err) {
    log.error('Check failed:', err.message);
    state.sendStatus({ status: 'error', message: err.message });
  } finally {
    state.checking = false;
  }
}

async function downloadUpdate(info, feed) {
  if (state.downloading) return;
  if (!info && state.lastInfo) ({ info, feed } = state.lastInfo);
  if (!info) throw new Error('No update info — call check first');
  state.downloading = true;

  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'stonic-update-'));
  const zipPath = path.join(workDir, 'update.zip');

  try {
    // ── Download with progress + streaming SHA512 ──
    const url = `${feed}/${encodeURIComponent(info.zipUrl)}`;
    log.info(`Downloading ${url}`);
    const res = await httpGet(url, { asStream: true });
    const total = parseInt(res.headers['content-length'] || '0', 10) || info.zipSize || 0;
    const hash = crypto.createHash('sha512');
    const out = fs.createWriteStream(zipPath);

    let transferred = 0;
    let lastTick = Date.now();
    let lastBytes = 0;
    await new Promise((resolve, reject) => {
      res.on('data', (chunk) => {
        hash.update(chunk);
        transferred += chunk.length;
        const now = Date.now();
        if (now - lastTick >= 500) {
          const bytesPerSecond = Math.round(((transferred - lastBytes) / (now - lastTick)) * 1000);
          state.sendStatus({
            status: 'downloading',
            percent: total ? Math.round((transferred / total) * 100) : 0,
            bytesPerSecond,
            transferred,
            total,
          });
          lastTick = now;
          lastBytes = transferred;
        }
      });
      res.pipe(out);
      out.on('finish', resolve);
      out.on('error', reject);
      res.on('error', reject);
    });

    // ── Integrity check (same guarantee as electron-updater) ──
    if (info.zipSha) {
      const digest = hash.digest('base64');
      if (digest !== info.zipSha) {
        throw new Error('SHA512 mismatch — corrupted or tampered download, refusing to install.');
      }
      log.info('SHA512 verified.');
    } else {
      log.warn('No sha512 in channel file — skipping integrity check.');
    }

    // ── Extract (.zip → .app) — ditto preserves signatures/symlinks ──
    const extractDir = path.join(workDir, 'extracted');
    fs.mkdirSync(extractDir);
    await execFileP('/usr/bin/ditto', ['-x', '-k', zipPath, extractDir]);
    const appName = fs.readdirSync(extractDir).find((e) => e.endsWith('.app'));
    if (!appName) throw new Error('No .app bundle inside the update zip');
    const newAppPath = path.join(extractDir, appName);

    // Belt & braces: strip any quarantine attribute so Gatekeeper never blocks.
    try { await execFileP('/usr/bin/xattr', ['-dr', 'com.apple.quarantine', newAppPath]); } catch { /* attr absent — fine */ }

    state.pending = { version: info.version, appPath: newAppPath, workDir };
    log.info(`Update ${info.version} downloaded & extracted, ready to install.`);
    state.sendStatus({ status: 'downloaded', version: info.version });
  } catch (err) {
    fs.rmSync(workDir, { recursive: true, force: true });
    log.error('Download failed:', err.message);
    state.sendStatus({ status: 'error', message: err.message });
  } finally {
    state.downloading = false;
  }
}

async function quitAndInstall() {
  const pending = state.pending;
  if (!pending) {
    log.warn('install requested but no update is downloaded.');
    return;
  }

  const currentApp = getCurrentAppBundlePath();
  if (!currentApp) {
    state.sendStatus({ status: 'error', message: 'Not running from a .app bundle — cannot self-update.' });
    return;
  }
  if (currentApp.includes('/AppTranslocation/')) {
    // macOS runs quarantined apps from a randomized read-only mount.
    dialog.showMessageBoxSync({
      type: 'info',
      message: 'Please move Stonic AI to the Applications folder first, then update again.',
    });
    return;
  }

  const backupPath = path.join(os.tmpdir(), `stonic-old-${Date.now()}.app`);
  try {
    log.info(`Installing ${pending.version}: swapping ${currentApp}`);
    // 1. Move the running bundle aside (allowed on macOS while running)
    await execFileP('/bin/mv', [currentApp, backupPath]);
    // 2. Move the new bundle into place
    try {
      await execFileP('/bin/mv', [pending.appPath, currentApp]);
    } catch (err) {
      // Rollback so the user is never left without an app
      await execFileP('/bin/mv', [backupPath, currentApp]).catch(() => {});
      throw err;
    }
    // 3. Old bundle + temp files cleanup (best-effort)
    fs.rmSync(backupPath, { recursive: true, force: true });
    fs.rmSync(pending.workDir, { recursive: true, force: true });

    // 4. Full quit, then reopen the NEW bundle (full close → reliable swap)
    log.info('Swap complete — restarting into the new version.');
    const reopen = spawn('/bin/sh', ['-c', `sleep 2; /usr/bin/open -n "${currentApp.replace(/"/g, '\\"')}"`], {
      detached: true,
      stdio: 'ignore',
    });
    reopen.unref();
    state.pending = null;
    app.exit(0);
  } catch (err) {
    log.error('Install failed:', err.message);
    state.sendStatus({ status: 'error', message: `Install failed: ${err.message}` });
  }
}

// ── Public wiring (mirrors the Windows electron-updater contract) ──

function setupMacUpdater({ getMainWindow, autoDownload }) {
  state.autoDownload = !!autoDownload;
  state.sendStatus = (data) => {
    try {
      const win = getMainWindow();
      if (win && !win.isDestroyed()) win.webContents.send('update-status', data);
    } catch { /* window gone */ }
  };

  ipcMain.handle('install-update', () => quitAndInstall());
  ipcMain.handle('check-for-updates', () => { checkForUpdates(); });

  // Same cadence as the Windows path: first check 5s after startup.
  setTimeout(() => checkForUpdates(), 5000);
  log.info(`Enabled (feed: ${getFeedUrl()}, autoDownload: ${state.autoDownload}).`);
}

function setMacAutoDownload(enabled) {
  state.autoDownload = !!enabled;
}

function macDownloadUpdate() {
  return downloadUpdate();
}

module.exports = {
  setupMacUpdater,
  setMacAutoDownload,
  macDownloadUpdate,
  // exported for tests
  parseChannelYml,
  isNewerVersion,
};
